-- ============================================================================
-- Migration 004: Fix Corrupted DCA Transactions
-- ============================================================================
-- BUG: dca-execute was storing amountUsdt (dollar amount) as coin quantity
-- when Bybit's placeOrder didn't return filled qty.
-- Example: $5 DCA into BTC was stored as amount=5 BTC (~$475,000)
--
-- This migration identifies and deletes these corrupted records.
-- They can be identified by:
--   1. notes contains 'DCA auto-buy' (auto-generated by dca-execute)
--   2. price_per_unit = 0 (never got the real price)
--   3. OR amount seems unreasonably high for the asset
-- ============================================================================

-- Delete DCA transactions where price_per_unit was 0 (no real fill data)
DELETE FROM public.transactions
WHERE notes LIKE '%DCA auto-buy%'
  AND price_per_unit = 0;

-- Delete DCA transactions where the USD value would be absurdly high
-- (amount * current rough price > $1M for a single transaction is suspicious)
-- BTC rough price ~$95k, so amount > 10 BTC in a single DCA is clearly wrong
DELETE FROM public.transactions
WHERE notes LIKE '%DCA auto-buy%'
  AND asset_symbol = 'BTC'
  AND amount > 1;

-- ETH rough price ~$3.5k, so amount > 50 ETH in a single DCA is wrong
DELETE FROM public.transactions
WHERE notes LIKE '%DCA auto-buy%'
  AND asset_symbol = 'ETH'
  AND amount > 10;

-- For other assets, if amount > 10000 in a single DCA execution, it's suspicious
DELETE FROM public.transactions
WHERE notes LIKE '%DCA auto-buy%'
  AND asset_symbol NOT IN ('BTC', 'ETH', 'USDT', 'USDC')
  AND amount > 10000;
